name: Web

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  deploy:
    name: Web
    runs-on: ubuntu-latest
    
    defaults:  
      run: |
        cd haste/
        

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        
      - name: Test
        run: yarn test
